
package telaGerador;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Guilherme Cordeiro
 */
public class GeradorYTLink extends javax.swing.JFrame {

    /**
     * Creates new form GeradorYTLink
     */
    public GeradorYTLink() {
        initComponents();
        panelResultado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Barra = new javax.swing.JPanel();
        jPaneFechar = new javax.swing.JPanel();
        icon_Close = new javax.swing.JLabel();
        jPaneMinimizar = new javax.swing.JPanel();
        icon_Mini = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Tela1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblURLVideo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtURLVideo = new javax.swing.JTextField();
        txtTituloVideo = new javax.swing.JTextField();
        lblTitleVideo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPaneHelp1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtAcessi = new javax.swing.JTextField();
        lblTitleAcess = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPaneHelp2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panelResultado = new javax.swing.JPanel();
        lblLinkGerado = new javax.swing.JLabel();
        txtResultado = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        btnGeradorLink = new javax.swing.JLabel();
        btnCopy = new javax.swing.JLabel();
        Tela2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nav = new javax.swing.JPanel();
        btnTelaPrincipal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        barSelecLink = new javax.swing.JPanel();
        btnTelaCreditos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        barSelecCred = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerador de Links");
        setMinimumSize(new java.awt.Dimension(753, 431));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(753, 431));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Barra.setBackground(new java.awt.Color(0, 0, 45));
        Barra.setFocusTraversalPolicyProvider(true);
        Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMouseDragged(evt);
            }
        });
        Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMousePressed(evt);
            }
        });

        jPaneFechar.setBackground(new java.awt.Color(0, 0, 45));
        jPaneFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPaneFecharMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPaneFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPaneFecharMouseExited(evt);
            }
        });

        icon_Close.setBackground(new java.awt.Color(255, 255, 255));
        icon_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_delete_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPaneFecharLayout = new javax.swing.GroupLayout(jPaneFechar);
        jPaneFechar.setLayout(jPaneFecharLayout);
        jPaneFecharLayout.setHorizontalGroup(
            jPaneFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneFecharLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_Close)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneFecharLayout.setVerticalGroup(
            jPaneFecharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(icon_Close)
        );

        jPaneMinimizar.setBackground(new java.awt.Color(0, 0, 45));
        jPaneMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPaneMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPaneMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPaneMinimizarMouseExited(evt);
            }
        });
        jPaneMinimizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_Mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/minimize_118918.png"))); // NOI18N
        icon_Mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_MiniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon_MiniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon_MiniMouseExited(evt);
            }
        });
        jPaneMinimizar.add(icon_Mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gerador de Links");

        javax.swing.GroupLayout BarraLayout = new javax.swing.GroupLayout(Barra);
        Barra.setLayout(BarraLayout);
        BarraLayout.setHorizontalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraLayout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(jPaneMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPaneFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BarraLayout.setVerticalGroup(
            BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BarraLayout.createSequentialGroup()
                .addGroup(BarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPaneFechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPaneMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 800, 30));

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));

        Tela1.setBackground(new java.awt.Color(112, 112, 153));
        Tela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tela1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(91, 91, 132));

        lblURLVideo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblURLVideo.setForeground(new java.awt.Color(255, 255, 255));
        lblURLVideo.setText("URL do vídeo do YouTube:");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        txtURLVideo.setBackground(new java.awt.Color(91, 91, 132));
        txtURLVideo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtURLVideo.setForeground(new java.awt.Color(204, 204, 204));
        txtURLVideo.setText("Cole aqui a URL do vídeo");
        txtURLVideo.setBorder(null);
        txtURLVideo.setName(""); // NOI18N
        txtURLVideo.setOpaque(false);
        txtURLVideo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtURLVideoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtURLVideoFocusLost(evt);
            }
        });

        txtTituloVideo.setBackground(new java.awt.Color(91, 91, 132));
        txtTituloVideo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTituloVideo.setForeground(new java.awt.Color(204, 204, 204));
        txtTituloVideo.setText("Insira o título do vídeo");
        txtTituloVideo.setBorder(null);
        txtTituloVideo.setName(""); // NOI18N
        txtTituloVideo.setOpaque(false);
        txtTituloVideo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTituloVideoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTituloVideoFocusLost(evt);
            }
        });

        lblTitleVideo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleVideo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleVideo.setText("Título do vídeo:");

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        jPaneHelp1.setBackground(new java.awt.Color(91, 91, 132));
        jPaneHelp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPaneHelp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPaneHelp1MouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_help_30px_2.png"))); // NOI18N

        javax.swing.GroupLayout jPaneHelp1Layout = new javax.swing.GroupLayout(jPaneHelp1);
        jPaneHelp1.setLayout(jPaneHelp1Layout);
        jPaneHelp1Layout.setHorizontalGroup(
            jPaneHelp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneHelp1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );
        jPaneHelp1Layout.setVerticalGroup(
            jPaneHelp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneHelp1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );

        txtAcessi.setBackground(new java.awt.Color(91, 91, 132));
        txtAcessi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAcessi.setForeground(new java.awt.Color(204, 204, 204));
        txtAcessi.setText("Insira o título de acessiblilidade");
        txtAcessi.setBorder(null);
        txtAcessi.setName(""); // NOI18N
        txtAcessi.setOpaque(false);
        txtAcessi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAcessiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAcessiFocusLost(evt);
            }
        });

        lblTitleAcess.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleAcess.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleAcess.setText("Título de acessibilidade:");

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        jPaneHelp2.setBackground(new java.awt.Color(91, 91, 132));
        jPaneHelp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPaneHelp2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPaneHelp2MouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_help_30px_2.png"))); // NOI18N

        javax.swing.GroupLayout jPaneHelp2Layout = new javax.swing.GroupLayout(jPaneHelp2);
        jPaneHelp2.setLayout(jPaneHelp2Layout);
        jPaneHelp2Layout.setHorizontalGroup(
            jPaneHelp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneHelp2Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );
        jPaneHelp2Layout.setVerticalGroup(
            jPaneHelp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneHelp2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );

        panelResultado.setBackground(new java.awt.Color(91, 91, 132));

        lblLinkGerado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLinkGerado.setForeground(new java.awt.Color(255, 255, 255));
        lblLinkGerado.setText("Link Gerado!");

        txtResultado.setBackground(new java.awt.Color(91, 91, 132));
        txtResultado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(204, 204, 204));
        txtResultado.setText("Aqui estará o link gerado");
        txtResultado.setBorder(null);
        txtResultado.setName(""); // NOI18N
        txtResultado.setOpaque(false);

        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelResultadoLayout = new javax.swing.GroupLayout(panelResultado);
        panelResultado.setLayout(panelResultadoLayout);
        panelResultadoLayout.setHorizontalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addGroup(panelResultadoLayout.createSequentialGroup()
                        .addComponent(lblLinkGerado)
                        .addContainerGap())
                    .addComponent(txtResultado)))
        );
        panelResultadoLayout.setVerticalGroup(
            panelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoLayout.createSequentialGroup()
                .addComponent(lblLinkGerado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(91, 91, 132));

        btnGeradorLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnLink.png"))); // NOI18N
        btnGeradorLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGeradorLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGeradorLinkMouseClicked(evt);
            }
        });

        btnCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnCopy.png"))); // NOI18N
        btnCopy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCopy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCopyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGeradorLink)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCopy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGeradorLink)
                    .addComponent(btnCopy))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblURLVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(605, 605, 605))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTitleVideo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPaneHelp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(txtTituloVideo))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTitleAcess)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPaneHelp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator3)
                                    .addComponent(txtAcessi, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)))
                            .addComponent(txtURLVideo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelResultado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(309, 309, 309))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblURLVideo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtURLVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitleVideo)
                            .addComponent(jPaneHelp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTituloVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTitleAcess)
                                .addGap(11, 11, 11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPaneHelp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(txtAcessi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Tela1Layout = new javax.swing.GroupLayout(Tela1);
        Tela1.setLayout(Tela1Layout);
        Tela1Layout.setHorizontalGroup(
            Tela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tela1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        Tela1Layout.setVerticalGroup(
            Tela1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tela1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", Tela1);

        Tela2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("Em construção!");

        javax.swing.GroupLayout Tela2Layout = new javax.swing.GroupLayout(Tela2);
        Tela2.setLayout(Tela2Layout);
        Tela2Layout.setHorizontalGroup(
            Tela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tela2Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jLabel1)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        Tela2Layout.setVerticalGroup(
            Tela2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tela2Layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(197, 197, 197))
        );

        jTabbedPane1.addTab("tab2", Tela2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -30, 610, 470));

        Nav.setBackground(new java.awt.Color(0, 0, 45));

        btnTelaPrincipal.setBackground(new java.awt.Color(33, 33, 68));
        btnTelaPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTelaPrincipalMouseClicked(evt);
            }
        });
        btnTelaPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_link_25px.png"))); // NOI18N
        btnTelaPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gerar Link");
        btnTelaPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 60));

        barSelecLink.setBackground(new java.awt.Color(229, 229, 229));

        javax.swing.GroupLayout barSelecLinkLayout = new javax.swing.GroupLayout(barSelecLink);
        barSelecLink.setLayout(barSelecLinkLayout);
        barSelecLinkLayout.setHorizontalGroup(
            barSelecLinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        barSelecLinkLayout.setVerticalGroup(
            barSelecLinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        btnTelaPrincipal.add(barSelecLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, -1));

        btnTelaCreditos.setBackground(new java.awt.Color(0, 0, 45));
        btnTelaCreditos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTelaCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTelaCreditosMouseClicked(evt);
            }
        });
        btnTelaCreditos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_info_25px.png"))); // NOI18N
        btnTelaCreditos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Créditos");
        btnTelaCreditos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 60));

        barSelecCred.setBackground(new java.awt.Color(229, 229, 229));

        javax.swing.GroupLayout barSelecCredLayout = new javax.swing.GroupLayout(barSelecCred);
        barSelecCred.setLayout(barSelecCredLayout);
        barSelecCredLayout.setHorizontalGroup(
            barSelecCredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        barSelecCredLayout.setVerticalGroup(
            barSelecCredLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        btnTelaCreditos.add(barSelecCred, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 4, -1));
        barSelecCred.setVisible(false);

        javax.swing.GroupLayout NavLayout = new javax.swing.GroupLayout(Nav);
        Nav.setLayout(NavLayout);
        NavLayout.setHorizontalGroup(
            NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(btnTelaCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NavLayout.setVerticalGroup(
            NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTelaCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        getContentPane().add(Nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 440));

        setSize(new java.awt.Dimension(783, 431));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int x = 0;
    int y = 0;
        
    private void btnTelaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTelaPrincipalMouseClicked
        jTabbedPane1.setSelectedIndex(0);
        focusIn(btnTelaPrincipal);
        focusOut(btnTelaCreditos);
        barSelecCred.setVisible(false);
        barSelecLink.setVisible(true);
    }//GEN-LAST:event_btnTelaPrincipalMouseClicked

    private void btnTelaCreditosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTelaCreditosMouseClicked
        jTabbedPane1.setSelectedIndex(1);
        focusIn(btnTelaCreditos);
        focusOut(btnTelaPrincipal);
        barSelecCred.setVisible(true);
        barSelecLink.setVisible(false);
    }//GEN-LAST:event_btnTelaCreditosMouseClicked

    private void BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_BarraMousePressed

    private void BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_BarraMouseDragged

    private void jPaneHelp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneHelp1MouseEntered
        jPaneHelp1.setBackground(new Color(73,73,107));
    }//GEN-LAST:event_jPaneHelp1MouseEntered

    private void jPaneHelp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneHelp1MouseExited
        jPaneHelp1.setBackground(new Color(91,91,132));
    }//GEN-LAST:event_jPaneHelp1MouseExited

    private void jPaneFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneFecharMouseExited
        jPaneFechar.setBackground(new Color(0,0,45));
    }//GEN-LAST:event_jPaneFecharMouseExited

    private void jPaneFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneFecharMouseEntered
        jPaneFechar.setBackground(new Color(33,33,68));
    }//GEN-LAST:event_jPaneFecharMouseEntered

    private void jPaneFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneFecharMouseClicked
        dispose();
    }//GEN-LAST:event_jPaneFecharMouseClicked

    private void jPaneMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneMinimizarMouseExited
        jPaneMinimizar.setBackground(new Color(0,0,45));
    }//GEN-LAST:event_jPaneMinimizarMouseExited

    private void jPaneMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneMinimizarMouseEntered
        jPaneMinimizar.setBackground(new Color(33,33,68));
    }//GEN-LAST:event_jPaneMinimizarMouseEntered

    private void jPaneMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneMinimizarMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jPaneMinimizarMouseClicked

    private void icon_MiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_MiniMouseExited
        jPaneMinimizar.setBackground(new Color(0,0,45));
    }//GEN-LAST:event_icon_MiniMouseExited

    private void icon_MiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_MiniMouseEntered
        jPaneMinimizar.setBackground(new Color(33,33,68));
    }//GEN-LAST:event_icon_MiniMouseEntered

    private void icon_MiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_MiniMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_icon_MiniMouseClicked

    private void txtURLVideoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtURLVideoFocusGained
        if(txtURLVideo.getText().equals("Cole aqui a URL do vídeo")){
            txtURLVideo.setText("");
        }
    }//GEN-LAST:event_txtURLVideoFocusGained

    private void txtTituloVideoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTituloVideoFocusGained
        if(txtTituloVideo.getText().equals("Insira o título do vídeo")){
            txtTituloVideo.setText("");
        }
    }//GEN-LAST:event_txtTituloVideoFocusGained

    private void txtAcessiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAcessiFocusGained
        if(txtAcessi.getText().equals("Insira o título de acessiblilidade")){
            txtAcessi.setText("");
        }
    }//GEN-LAST:event_txtAcessiFocusGained

    private void jPaneHelp2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneHelp2MouseEntered
        jLabel10.setBackground(new Color(73,73,107));
    }//GEN-LAST:event_jPaneHelp2MouseEntered

    private void jPaneHelp2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneHelp2MouseExited
        jPaneHelp2.setBackground(new Color(91,91,132));
    }//GEN-LAST:event_jPaneHelp2MouseExited

    private void txtURLVideoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtURLVideoFocusLost
        if(txtURLVideo.getText().equals("")){
            txtURLVideo.setText("Cole aqui a URL do vídeo");
        }
    }//GEN-LAST:event_txtURLVideoFocusLost

    private void txtTituloVideoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTituloVideoFocusLost
        if(txtTituloVideo.getText().equals("")){
            txtTituloVideo.setText("Insira o título do vídeo");
        }
    }//GEN-LAST:event_txtTituloVideoFocusLost

    private void txtAcessiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAcessiFocusLost
        if(txtAcessi.getText().equals("")){
            txtAcessi.setText("Insira o título de acessiblilidade");
        }
    }//GEN-LAST:event_txtAcessiFocusLost

    private void btnGeradorLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGeradorLinkMouseClicked
        if(btnGeradorLink.getIcon().toString().contains("/imagens/btnLink.png")){
            String url = txtURLVideo.getText();
            String imgTitle = txtTituloVideo.getText();
            String videoAlt = txtAcessi.getText();
            //Campo da URL inválido
            if(url.equals("Cole aqui a URL do vídeo") || url.equals("")){
                JOptionPane.showMessageDialog(null, "O campo \"" + lblURLVideo.getText().replace(":", "") + "\" está vazia.", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                //Campo do título inválido
            }else if(imgTitle.equals("Insira o título do vídeo") || imgTitle.equals("")){
                JOptionPane.showMessageDialog(null, "O campo \"" + lblTitleVideo.getText().replace(":", "") + "\" está vazia.", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                //Campo da descrição de acessibilidade inválido
            }else if(videoAlt.equals("Insira o título de acessiblilidade") || videoAlt.equals("")){
                Object[] opt = {"Sim", "Não"};
                int resp = JOptionPane.showOptionDialog(null, "O campo \"" + lblTitleAcess.getText().replace(":", "") + 
                        "\" está vazia (campo não obrigatório). Quer continuar mesmo assim?", "IMPORTANTE",
                        JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, opt, opt[1]);
                if(resp == 0){ //SIM
                    videoAlt = "Clique aqui para ver o vídeo";
                    gerarLink(url, imgTitle, videoAlt);
                }       
            }else{
                gerarLink(url, imgTitle, videoAlt);
            }
        }else if(btnGeradorLink.getIcon().toString().contains("/imagens/btnClean.png")){
            txtURLVideo.setText("Cole aqui a URL do vídeo");
            txtTituloVideo.setText("Insira o título do vídeo");
            txtAcessi.setText("Insira o título de acessiblilidade");
            lblLinkGerado.setText("Link Gerado!");
            txtResultado.setText("");
            panelResultado.setVisible(false);
            Tela1.requestFocusInWindow();
            btnGeradorLink.setIcon(new ImageIcon(getClass().getResource("/imagens/btnLink.png")));
        }
        
    }//GEN-LAST:event_btnGeradorLinkMouseClicked

    private void btnCopyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCopyMouseClicked
        if(panelResultado.isVisible()){
            StringSelection strSelec = new StringSelection(txtResultado.getText());
            Clipboard clip = Toolkit.getDefaultToolkit().getSystemClipboard();
            clip.setContents(strSelec, null);
            //Trocar botão para 'btnCopied'
            //btnCopy.setIcon(new ImageIcon(getClass().getResource("/imagens/btnCopied.png")));
            lblLinkGerado.setText("Texto Copiado!");
        }else{
            JOptionPane.showMessageDialog(null, "Impossível copiar texto. O link ainda não foi gerado.", "URL não encontrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCopyMouseClicked

    private void Tela1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tela1MouseClicked
        Tela1.requestFocusInWindow();
    }//GEN-LAST:event_Tela1MouseClicked

    public void focusIn(JPanel panel){
        panel.setBackground(new Color(33,33,68));
    }
    
    public void focusOut(JPanel panel){
        panel.setBackground(new Color(0,0,45));
    }
    
    public void hover(JPanel panel){
        panel.setBackground(new Color(71,15,127));
    }
    
    public String trocarImg(String img){
        return "";
    }
    
    public int gerarLink(String url, String imgTitle, String videoAlt){
        char link[] = url.toCharArray();
        char[] converter = new char[11];
        
        //Considerando um link inválido
        if(!url.contains("youtu.be") && !url.contains("youtube.com")){
            JOptionPane.showMessageDialog(null, "URL inválida. Verifique a URL e tente novamente (URL oriunda de uma playlist não funciona).", "ERRO", JOptionPane.ERROR_MESSAGE);
            return 0;
        //Considerando o link encurtado do YouTube
        }else if(url.contains("youtu.be")){
            for(int c = 0; c < 11; c ++){
                converter[c] = link[17 + c];
            }
        //Considerando o link padrão do YouTube
        }else if(url.contains("youtube.com")){
            for(int c = 0; c < 11; c ++){
                converter[c] = link[32 + c];
            }
        }
        String IDVideo = new String(converter);
        txtResultado.setText("[![" + imgTitle + "](https://img.youtube.com/vi/" + IDVideo + "/0.jpg)](" + url + " \"" + videoAlt + "\")");
        panelResultado.setVisible(true);
        btnGeradorLink.setIcon(new ImageIcon(getClass().getResource("/imagens/btnClean.png")));
        return 0;
    }
    
    public void pausa(int ms){
    try{
        Thread.sleep(ms);
    }catch(InterruptedException ex){
        Thread.currentThread().interrupt();
    }
}
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeradorYTLink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeradorYTLink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeradorYTLink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeradorYTLink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeradorYTLink().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JPanel Nav;
    private javax.swing.JPanel Tela1;
    private javax.swing.JPanel Tela2;
    private javax.swing.JPanel barSelecCred;
    private javax.swing.JPanel barSelecLink;
    private javax.swing.JLabel btnCopy;
    private javax.swing.JLabel btnGeradorLink;
    private javax.swing.JPanel btnTelaCreditos;
    private javax.swing.JPanel btnTelaPrincipal;
    private javax.swing.JLabel icon_Close;
    private javax.swing.JLabel icon_Mini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPaneFechar;
    private javax.swing.JPanel jPaneHelp1;
    private javax.swing.JPanel jPaneHelp2;
    private javax.swing.JPanel jPaneMinimizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblLinkGerado;
    private javax.swing.JLabel lblTitleAcess;
    private javax.swing.JLabel lblTitleVideo;
    private javax.swing.JLabel lblURLVideo;
    private javax.swing.JPanel panelResultado;
    private javax.swing.JTextField txtAcessi;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtTituloVideo;
    private javax.swing.JTextField txtURLVideo;
    // End of variables declaration//GEN-END:variables
}
