/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telaGerador;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Guilherme Cordeiro
 */
public class PopUpModelo extends javax.swing.JFrame {

    /**
     * Creates new form avisoTituloVideo
     */
    public PopUpModelo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Barra7 = new javax.swing.JPanel();
        jPaneFechar7 = new javax.swing.JPanel();
        icon_Close7 = new javax.swing.JLabel();
        jPaneMinimizar = new javax.swing.JPanel();
        icon_Mini = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 45));

        jPanel2.setBackground(new java.awt.Color(33, 33, 68));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Impossível copiar texto. O link ainda não foi gerado.");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 70, -1));

        Barra7.setBackground(new java.awt.Color(0, 0, 45));
        Barra7.setFocusTraversalPolicyProvider(true);
        Barra7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Barra7MouseDragged(evt);
            }
        });
        Barra7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Barra7MousePressed(evt);
            }
        });

        jPaneFechar7.setBackground(new java.awt.Color(0, 0, 45));
        jPaneFechar7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPaneFechar7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPaneFechar7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPaneFechar7MouseExited(evt);
            }
        });

        icon_Close7.setBackground(new java.awt.Color(255, 255, 255));
        icon_Close7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_delete_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPaneFechar7Layout = new javax.swing.GroupLayout(jPaneFechar7);
        jPaneFechar7.setLayout(jPaneFechar7Layout);
        jPaneFechar7Layout.setHorizontalGroup(
            jPaneFechar7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneFechar7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(icon_Close7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneFechar7Layout.setVerticalGroup(
            jPaneFechar7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_Close7, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPaneMinimizar.setBackground(new java.awt.Color(0, 0, 45));
        jPaneMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPaneMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPaneMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPaneMinimizarMouseExited(evt);
            }
        });
        jPaneMinimizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_Mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/minimize_118918.png"))); // NOI18N
        icon_Mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_MiniMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon_MiniMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon_MiniMouseExited(evt);
            }
        });
        jPaneMinimizar.add(icon_Mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ERRO");

        javax.swing.GroupLayout Barra7Layout = new javax.swing.GroupLayout(Barra7);
        Barra7.setLayout(Barra7Layout);
        Barra7Layout.setHorizontalGroup(
            Barra7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(91, 91, 91)
                .addComponent(jPaneMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPaneFechar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Barra7Layout.setVerticalGroup(
            Barra7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Barra7Layout.createSequentialGroup()
                .addGroup(Barra7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPaneFechar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPaneMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addComponent(Barra7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Barra7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int x = 0;
    int y = 0;
        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPaneFechar7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneFechar7MouseClicked
        this.dispose();
    }//GEN-LAST:event_jPaneFechar7MouseClicked

    private void jPaneFechar7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneFechar7MouseEntered
        jPaneFechar.setBackground(new Color(33,33,68));
    }//GEN-LAST:event_jPaneFechar7MouseEntered

    private void jPaneFechar7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneFechar7MouseExited
        jPaneFechar.setBackground(new Color(0,0,45));
    }//GEN-LAST:event_jPaneFechar7MouseExited

    private void icon_MiniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_MiniMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_icon_MiniMouseClicked

    private void icon_MiniMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_MiniMouseEntered
        jPaneMinimizar.setBackground(new Color(33,33,68));
    }//GEN-LAST:event_icon_MiniMouseEntered

    private void icon_MiniMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_MiniMouseExited
        jPaneMinimizar.setBackground(new Color(0,0,45));
    }//GEN-LAST:event_icon_MiniMouseExited

    private void jPaneMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneMinimizarMouseClicked
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jPaneMinimizarMouseClicked

    private void jPaneMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneMinimizarMouseEntered
        jPaneMinimizar.setBackground(new Color(33,33,68));
    }//GEN-LAST:event_jPaneMinimizarMouseEntered

    private void jPaneMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPaneMinimizarMouseExited
        jPaneMinimizar.setBackground(new Color(0,0,45));
    }//GEN-LAST:event_jPaneMinimizarMouseExited

    private void Barra7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra7MouseDragged
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();

        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_Barra7MouseDragged

    private void Barra7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Barra7MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_Barra7MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUpModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUpModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUpModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUpModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUpModelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JPanel Barra1;
    private javax.swing.JPanel Barra2;
    private javax.swing.JPanel Barra3;
    private javax.swing.JPanel Barra4;
    private javax.swing.JPanel Barra5;
    private javax.swing.JPanel Barra6;
    private javax.swing.JPanel Barra7;
    private javax.swing.JLabel icon_Close;
    private javax.swing.JLabel icon_Close1;
    private javax.swing.JLabel icon_Close2;
    private javax.swing.JLabel icon_Close3;
    private javax.swing.JLabel icon_Close4;
    private javax.swing.JLabel icon_Close5;
    private javax.swing.JLabel icon_Close6;
    private javax.swing.JLabel icon_Close7;
    private javax.swing.JLabel icon_Mini;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPaneFechar;
    private javax.swing.JPanel jPaneFechar1;
    private javax.swing.JPanel jPaneFechar2;
    private javax.swing.JPanel jPaneFechar3;
    private javax.swing.JPanel jPaneFechar4;
    private javax.swing.JPanel jPaneFechar5;
    private javax.swing.JPanel jPaneFechar6;
    private javax.swing.JPanel jPaneFechar7;
    private javax.swing.JPanel jPaneMinimizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
